# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
# $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

num = 100
fibo = []

def getFibotillN(n):
    for _ in range(n):
        if(_==0 or _==1):
            fibo.append(_+1)
            continue
        newfibo = fibo[_-1]+fibo[_-2]
        if not (newfibo<4000000):
            break
        else:
            fibo.append(newfibo)
    print(f'The fibonacci series of first {n} numbers is: {fibo}')
    
def addEvenInArr(arr):
    sum =0
    for a in arr:
        if(a%2==0):
            sum = sum + a
    print(f'The sum of even numbers in array is {sum}')


getFibotillN(num)
addEvenInArr(fibo)